import Head from 'next/head'
import Image from 'next/image'


import { Box, Typography } from '@mui/material'
import { PageWrapper } from '@/components/PageWrapper'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageWrapper>
       
      </PageWrapper>
    </>
  )
}
